export const permissions = {
  AdminAllPermissions: 'admin:all_permissions',
  AccessDiscover: 'access:discover',
  AccessFiles: 'access:files',
  AccessMap: 'access:map',
  AccessMembers: 'access:members',
  AccessMyProjects: 'access:my_projects',
  AccessPosts: 'access:posts',
  AccessTasks: 'access:tasks',
  CreateMapMarker: 'create:map_marker',
  CreatePost: 'create:post',
  CreateReply: 'create:reply',
  CreateTask: 'create:task',
  DeleteFile: 'delete:file',
  DeleteMapMarker: 'delete:map_marker',
  EditMapMarker: 'edit:map_marker',
  EditTask: 'edit:task',
  ModifyCurrentProjectStage: 'modify:current_project_stage',
  UploadFile: 'upload:file',
};
