spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: elevate-connect
  devtools:
    restart:
      exclude: 'org/sds/elevateconnect/mapper/**,static/**,templates/**'
      poll-interval: 1000
      quiet-period: 400
      enabled: true
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}

mybatis:
  mapper-locations: classpath:org/sds/elevateconnect/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false
    aggressive-lazy-loading: false

miro:
  client-id: ${VITE_MIRO_CLIENT_ID}
  client-secret: ${VITE_MIRO_CLIENT_SECRET}

jwt:
  sign-key: ${JWT_SIGN_KEY}

frontend:
  url: ${FRONTEND_URL}