spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: elevate-connect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    host: ${SMTP_HOST}
    port: 465
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
      credentials:
        location: "file:src/main/resources/serviceAccountKey.json"

mybatis:
  mapper-locations: classpath:org/sds/elevateconnect/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false
    aggressive-lazy-loading: false

miro:
  client-id: ${VITE_MIRO_CLIENT_ID}
  client-secret: ${VITE_MIRO_CLIENT_SECRET}

jwt:
  sign-key: ${JWT_SIGN_KEY}

frontend:
  url: ${FRONTEND_URL}
