spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

server:
  port: ${PORT:8080}

logging:
  level:
    org.mybatis: INFO
    org.sds.elevateconnect: INFO
    org.springframework.security: INFO
